language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-4.8-dev
           - pandoc

script:
- if [[ $(uname -s) == 'Darwin' ]]; then brew install pandoc || true; fi;
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- nm $(./mason prefix ${MASON_NAME} ${MASON_VERSION})/bin/osmium | grep "GLIBC" | c++filt  || true
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
